version: "3.9"

services:
  db:
    image: postgres:16
    container_name: buinzoo-postgres
    restart: always
    environment:
      POSTGRES_USER: buinzoo
      POSTGRES_PASSWORD: buinzoo_password
      POSTGRES_DB: buinzoo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zoo_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U buinzoo"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .              # <--- CAMBIO: Ahora miramos desde la raíz
      dockerfile: back/Dockerfile  # <--- CAMBIO: Apuntamos al archivo específico
    container_name: zoo_backend
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: buinzoo
      POSTGRES_PASSWORD: buinzoo_password
      POSTGRES_DB: buinzoo
      SECRET_KEY: super_secret_dev_key_change_in_prod
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - zoo_net

  frontend:
    build:
      context: ./front/my-app
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://127.0.0.1:8000
    container_name: zoo_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - zoo_net

  vision_caracal:
    build: 
      context: .              # <--- CAMBIO: Miramos desde la raíz
      dockerfile: vision/Dockerfile # <--- CAMBIO: Apuntamos al archivo específico
    container_name: caracal_eyes
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - API_URL=http://web:8000/api/events
      - RTSP_LEFT=rtsp://view:vieW.,star3250@190.8.125.219:554/cam/realmonitor?channel=2&subtype=0
      - RTSP_RIGHT=rtsp://view:vieW.,star3250@190.8.125.219:554/cam/realmonitor?channel=1&subtype=0
    volumes:
      # Ajuste en el volumen: la ruta local ahora debe incluir 'vision/' porque el contexto cambió
      - ./vision/yolo_model:/app/yolo_model
    depends_on:
      - web
    networks:
      - zoo_net

networks:
  zoo_net:
    driver: bridge

volumes:
  postgres_data: